### ISSUE TITLE
file not found: raft_pointtrackSTIR/version

### ISSUE THREAD

**Issue by MichaelWangGo** [athaddius/STIRMetrics#7]
Thank you very much answering my question! I met a new problem:

Traceback (most recent call last):
  File "datatest/flow2d.py", line 205, in <module>
    end_estimates = trackanddisplay(
  File "datatest/flow2d.py", line 98, in trackanddisplay
    model = modeldict[modeltype]()
  File "/workspace/STIRMetrics/src/datatest/raft.py", line 26, in __init__
    self.tracker = torch.jit.load(TORCHSCRIPTFILE).to(self.device)
  File "/root/miniconda3/envs/raft/lib/python3.8/site-packages/torch/jit/__init__.py", line 275, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: [enforce fail at inline_container.cc:209] . file not found: raft_pointtrackSTIR/version

 I am sure that the path to raft_pointtrackSTIR.pt and other models is correct. What other reasons can cause this problem?

**Comment by MichaelWangGo** [comment]
I got it. raft only works for flow3d
